<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup><ItemGroup><PackageReference Include="Bonsai.Core" Version="2.9.0" /><PackageReference Include="YamlDotNet" Version="16.0.0" /><PackageReference Include="Newtonsoft.Json" Version="13.0.3" /><PackageReference Include="NJsonSchema.CodeGeneration" Version="10.9.0" /><PackageReference Include="NJsonSchema.CodeGeneration.CSharp" Version="10.9.0" /><PackageReference Include="NJsonSchema.Yaml" Version="10.9.0" /><PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" /><PackageReference Include="System.CodeDom" Version="8.0.0" /></ItemGroup></Project>